artifactId=azure-svc-bus
group=com.rubensgomes
description=Spring Boot demo integrating Azure Service Bus messaging
title=Azure Service Bus Demo
mainClass=com.rubensgomes.azure.svcbus.App

# version must end in SNAPSHOT for release plugin to work due to bug reported at:
# https://stackoverflow.com/questions/79675543/gradle-release-plugin-not-merging-main-to-release
version=0.0.1-SNAPSHOT

